// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type Kv struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Server struct {
	ID   int64  `json:"id"`
	Data string `json:"data"`
}

type User struct {
	ID   string `json:"id"`
	Data string `json:"data"`
}

type UserConnection struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	ServerID int64  `json:"server_id"`
	Protocol string `json:"protocol"`
	ClientID string `json:"client_id"`
	Data     string `json:"data"`
}
