// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	AddConnection(ctx context.Context, arg AddConnectionParams) error
	AddServer(ctx context.Context, data string) (int64, error)
	AddUser(ctx context.Context, arg AddUserParams) error
	AdjustConnectionServerIDs(ctx context.Context, serverID int64) error
	DeleteConnection(ctx context.Context, id string) error
	DeleteServer(ctx context.Context, id int64) error
	DeleteServerConnections(ctx context.Context, serverID int64) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserConnections(ctx context.Context, userID string) error
	GetAllSettings(ctx context.Context) ([]Kv, error)
	GetAllUserConnections(ctx context.Context) ([]string, error)
	GetConnectionByClient(ctx context.Context, arg GetConnectionByClientParams) (string, error)
	GetServer(ctx context.Context, id int64) (string, error)
	GetServerConnections(ctx context.Context, serverID int64) ([]string, error)
	GetServerConnectionsByProtocol(ctx context.Context, arg GetServerConnectionsByProtocolParams) ([]string, error)
	GetServers(ctx context.Context) ([]Server, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetUser(ctx context.Context, id string) (string, error)
	GetUserByUsername(ctx context.Context, data string) (User, error)
	GetUserConnections(ctx context.Context, userID string) ([]string, error)
	GetUsers(ctx context.Context) ([]User, error)
	GetUsersConnectionCounts(ctx context.Context) ([]GetUsersConnectionCountsRow, error)
	HasUsers(ctx context.Context) (int64, error)
	ReorderServersUpdateIDTemp(ctx context.Context, arg ReorderServersUpdateIDTempParams) error
	ReorderUserConnectionsNegative(ctx context.Context) error
	ReorderUserConnectionsUpdateServerIDTemp(ctx context.Context, arg ReorderUserConnectionsUpdateServerIDTempParams) error
	SetSetting(ctx context.Context, arg SetSettingParams) error
	UpdateConnection(ctx context.Context, arg UpdateConnectionParams) error
	UpdateServer(ctx context.Context, arg UpdateServerParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
