// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
)

const addConnection = `-- name: AddConnection :exec
INSERT INTO user_connections (id, user_id, server_id, protocol, client_id, data) 
VALUES (?, ?, ?, ?, ?, ?)
`

type AddConnectionParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	ServerID int64  `json:"server_id"`
	Protocol string `json:"protocol"`
	ClientID string `json:"client_id"`
	Data     string `json:"data"`
}

func (q *Queries) AddConnection(ctx context.Context, arg AddConnectionParams) error {
	_, err := q.exec(ctx, q.addConnectionStmt, addConnection,
		arg.ID,
		arg.UserID,
		arg.ServerID,
		arg.Protocol,
		arg.ClientID,
		arg.Data,
	)
	return err
}

const addServer = `-- name: AddServer :one
INSERT INTO servers (data) VALUES (?) RETURNING id
`

func (q *Queries) AddServer(ctx context.Context, data string) (int64, error) {
	row := q.queryRow(ctx, q.addServerStmt, addServer, data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addUser = `-- name: AddUser :exec
INSERT INTO users (id, data) VALUES (?, ?)
ON CONFLICT(id) DO UPDATE SET data = excluded.data
`

type AddUserParams struct {
	ID   string `json:"id"`
	Data string `json:"data"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.exec(ctx, q.addUserStmt, addUser, arg.ID, arg.Data)
	return err
}

const adjustConnectionServerIDs = `-- name: AdjustConnectionServerIDs :exec
UPDATE user_connections SET server_id = server_id - 1 WHERE server_id > ?
`

func (q *Queries) AdjustConnectionServerIDs(ctx context.Context, serverID int64) error {
	_, err := q.exec(ctx, q.adjustConnectionServerIDsStmt, adjustConnectionServerIDs, serverID)
	return err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM user_connections WHERE id = ?
`

func (q *Queries) DeleteConnection(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteConnectionStmt, deleteConnection, id)
	return err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = ?
`

func (q *Queries) DeleteServer(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteServerStmt, deleteServer, id)
	return err
}

const deleteServerConnections = `-- name: DeleteServerConnections :exec
DELETE FROM user_connections WHERE server_id = ?
`

func (q *Queries) DeleteServerConnections(ctx context.Context, serverID int64) error {
	_, err := q.exec(ctx, q.deleteServerConnectionsStmt, deleteServerConnections, serverID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	return err
}

const deleteUserConnections = `-- name: DeleteUserConnections :exec
DELETE FROM user_connections WHERE user_id = ?
`

func (q *Queries) DeleteUserConnections(ctx context.Context, userID string) error {
	_, err := q.exec(ctx, q.deleteUserConnectionsStmt, deleteUserConnections, userID)
	return err
}

const getAllSettings = `-- name: GetAllSettings :many
SELECT key, value FROM kv
`

func (q *Queries) GetAllSettings(ctx context.Context) ([]Kv, error) {
	rows, err := q.query(ctx, q.getAllSettingsStmt, getAllSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kv
	for rows.Next() {
		var i Kv
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserConnections = `-- name: GetAllUserConnections :many
SELECT data FROM user_connections
`

func (q *Queries) GetAllUserConnections(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.getAllUserConnectionsStmt, getAllUserConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConnectionByClient = `-- name: GetConnectionByClient :one
SELECT data FROM user_connections WHERE server_id = ? AND protocol = ? AND client_id = ? LIMIT 1
`

type GetConnectionByClientParams struct {
	ServerID int64  `json:"server_id"`
	Protocol string `json:"protocol"`
	ClientID string `json:"client_id"`
}

func (q *Queries) GetConnectionByClient(ctx context.Context, arg GetConnectionByClientParams) (string, error) {
	row := q.queryRow(ctx, q.getConnectionByClientStmt, getConnectionByClient, arg.ServerID, arg.Protocol, arg.ClientID)
	var data string
	err := row.Scan(&data)
	return data, err
}

const getServer = `-- name: GetServer :one
SELECT data FROM servers WHERE id = ? LIMIT 1
`

func (q *Queries) GetServer(ctx context.Context, id int64) (string, error) {
	row := q.queryRow(ctx, q.getServerStmt, getServer, id)
	var data string
	err := row.Scan(&data)
	return data, err
}

const getServerConnections = `-- name: GetServerConnections :many
SELECT data FROM user_connections WHERE server_id = ?
`

func (q *Queries) GetServerConnections(ctx context.Context, serverID int64) ([]string, error) {
	rows, err := q.query(ctx, q.getServerConnectionsStmt, getServerConnections, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerConnectionsByProtocol = `-- name: GetServerConnectionsByProtocol :many
SELECT data FROM user_connections WHERE server_id = ? AND protocol = ?
`

type GetServerConnectionsByProtocolParams struct {
	ServerID int64  `json:"server_id"`
	Protocol string `json:"protocol"`
}

func (q *Queries) GetServerConnectionsByProtocol(ctx context.Context, arg GetServerConnectionsByProtocolParams) ([]string, error) {
	rows, err := q.query(ctx, q.getServerConnectionsByProtocolStmt, getServerConnectionsByProtocol, arg.ServerID, arg.Protocol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServers = `-- name: GetServers :many
SELECT id, data FROM servers ORDER BY id
`

func (q *Queries) GetServers(ctx context.Context) ([]Server, error) {
	rows, err := q.query(ctx, q.getServersStmt, getServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Server
	for rows.Next() {
		var i Server
		if err := rows.Scan(&i.ID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM kv WHERE key = ? LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.queryRow(ctx, q.getSettingStmt, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUser = `-- name: GetUser :one
SELECT data FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (string, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var data string
	err := row.Scan(&data)
	return data, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, data FROM users WHERE json_extract(data, '$.username') = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, data string) (User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, data)
	var i User
	err := row.Scan(&i.ID, &i.Data)
	return i, err
}

const getUserConnections = `-- name: GetUserConnections :many
SELECT data FROM user_connections WHERE user_id = ?
`

func (q *Queries) GetUserConnections(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.query(ctx, q.getUserConnectionsStmt, getUserConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsers = `-- name: GetUsers :many
SELECT id, data FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.getUsersStmt, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersConnectionCounts = `-- name: GetUsersConnectionCounts :many
SELECT user_id, COUNT(*) as count
FROM user_connections
GROUP BY user_id
`

type GetUsersConnectionCountsRow struct {
	UserID string `json:"user_id"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetUsersConnectionCounts(ctx context.Context) ([]GetUsersConnectionCountsRow, error) {
	rows, err := q.query(ctx, q.getUsersConnectionCountsStmt, getUsersConnectionCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersConnectionCountsRow
	for rows.Next() {
		var i GetUsersConnectionCountsRow
		if err := rows.Scan(&i.UserID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUsers = `-- name: HasUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) HasUsers(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.hasUsersStmt, hasUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const reorderServersUpdateIDTemp = `-- name: ReorderServersUpdateIDTemp :exec
UPDATE servers SET id = ? WHERE id = ?
`

type ReorderServersUpdateIDTempParams struct {
	ID   int64 `json:"id"`
	ID_2 int64 `json:"id_2"`
}

func (q *Queries) ReorderServersUpdateIDTemp(ctx context.Context, arg ReorderServersUpdateIDTempParams) error {
	_, err := q.exec(ctx, q.reorderServersUpdateIDTempStmt, reorderServersUpdateIDTemp, arg.ID, arg.ID_2)
	return err
}

const reorderUserConnectionsNegative = `-- name: ReorderUserConnectionsNegative :exec
UPDATE user_connections SET server_id = -server_id - 1
`

func (q *Queries) ReorderUserConnectionsNegative(ctx context.Context) error {
	_, err := q.exec(ctx, q.reorderUserConnectionsNegativeStmt, reorderUserConnectionsNegative)
	return err
}

const reorderUserConnectionsUpdateServerIDTemp = `-- name: ReorderUserConnectionsUpdateServerIDTemp :exec
UPDATE user_connections SET server_id = ? WHERE server_id = ?
`

type ReorderUserConnectionsUpdateServerIDTempParams struct {
	ServerID   int64 `json:"server_id"`
	ServerID_2 int64 `json:"server_id_2"`
}

func (q *Queries) ReorderUserConnectionsUpdateServerIDTemp(ctx context.Context, arg ReorderUserConnectionsUpdateServerIDTempParams) error {
	_, err := q.exec(ctx, q.reorderUserConnectionsUpdateServerIDTempStmt, reorderUserConnectionsUpdateServerIDTemp, arg.ServerID, arg.ServerID_2)
	return err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO kv (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.exec(ctx, q.setSettingStmt, setSetting, arg.Key, arg.Value)
	return err
}

const updateConnection = `-- name: UpdateConnection :exec
UPDATE user_connections SET data = ? WHERE id = ?
`

type UpdateConnectionParams struct {
	Data string `json:"data"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) error {
	_, err := q.exec(ctx, q.updateConnectionStmt, updateConnection, arg.Data, arg.ID)
	return err
}

const updateServer = `-- name: UpdateServer :exec
UPDATE servers SET data = ? WHERE id = ?
`

type UpdateServerParams struct {
	Data string `json:"data"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) error {
	_, err := q.exec(ctx, q.updateServerStmt, updateServer, arg.Data, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET data = ? WHERE id = ?
`

type UpdateUserParams struct {
	Data string `json:"data"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.exec(ctx, q.updateUserStmt, updateUser, arg.Data, arg.ID)
	return err
}
