services:
  amnezia_panel:
    build:
      context: .
      dockerfile: Dockerfile
    # image: prvtpro/amnezia-panel:latest
    container_name: amnezia_panel

    ports:
      - "${APP_PORT:-8000}:8000"

    environment:
      - DB_PATH=/data/panel.db

    volumes:
      - amnezia_data:/data

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8000/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  amnezia_data:
